name: Build Beacon and Upload to Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci --include=optional
      - run: npm run build:beacon
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: apps/web/dist/beacon.coffee/browser
      - run: ls dist/beacon.coffee/browser
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --overwrite true --account-name hornbeam --auth-mode key -d 'beacon' -s apps/web/dist/beacon.coffee/browser

      - name: logout
        run: |
          az logout
        if: always()
